version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - "3311:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 123

  adminer:
    image: adminer
    restart: always
    ports:
      - 8061:8080